// 将 rank 抽离出来，在此方便维护
// 规定只有 home 路由的 rank 才能为 0

const home = 0,
  systemManagement = 1,
  thesisManagement = 2,
  dataStatistics = 3,
  noticeManagement = 4,
  topicManagement = 11,
  supervisedStudents = 12,
  dataManagement = 13,
  defenseManagement = 14,
  evaluationManagement = 15,
  thesisTopicSelection = 21,
  modifyTheTopic = 22,
  supervisedTeacher = 23,
  submitData = 24,
  defenseInformation = 25,
  checkTheScore = 26,
  user = 31,
  schoolWebsite = 32,
  guide = 33,
  about = 34,
  error = 35;

export {
  home,
  systemManagement,
  thesisManagement,
  dataStatistics,
  noticeManagement,
  topicManagement,
  supervisedStudents,
  dataManagement,
  defenseManagement,
  evaluationManagement,
  thesisTopicSelection,
  modifyTheTopic,
  supervisedTeacher,
  submitData,
  defenseInformation,
  checkTheScore,
  user,
  schoolWebsite,
  guide,
  about,
  error
};
